INSERT INTO Oggetti 
VALUES
(1,'Olivetti Summa 15','http://192.168.1.1:3000/static/1.jpg'),
(2,'Olivetti MC 24','no_img'),
(3,'Burroughs Ten Key','no_img'),
(4,'Olivetti 101 Perottina 1445','no_img'),
(5,'Olivetti Divisumma 26 G.T.','no_img'),
(6,'Olivetti Logos 240','no_img'),
(7,'Olivetti MiniDisk','no_img');

INSERT INTO Descrizioni(oggetto,posizione,tipo,info)
VALUES
(1,0,'immagine','https://upload.wikimedia.org/wikipedia/commons/b/b1/Olivetti_Summa_15.jpg'),
(1,1,'titolo','Marca:'),
(1,2,'testo','Olivetti'),
(1,3,'titolo','Anno:'),
(1,4,'testo','1949'),
(1,5,'testo','La Summa15 è una addizionatrice meccanica manuale realizzata dalla Olivetti. Una caratteristica innovativa di questa macchina è il meccanismo a quattro vie progettato e brevettato da Natale Capellaro. Era la nascita del primo vero e proprio joystick. E\’ interessante sapere che nonostante fosse un’addizionatrice, la Summa 15 è capace anche di fare moltiplicazioni, seppure fino a 9.'),
(2,0,'titolo','Marca:'),
(2,1,'testo','Olivetti'),
(2,2,'titolo','Anno:'),
(2,3,'testo','1956'),
(2,4,'testo','Macchine da calcolo elettriche, automatiche, con stampa integrata e registro di memoria dinamica: tutto questo è la serie di macchine prodotte dall\'azienda italiana Olivetti a partire dal 1956. Il modello più famoso e venduto, in milioni di unità, è in assoluto la Divisumma 24. Essa rappresentò una rivoluzione nel settore dei calcolatori automatici diventando anche un\'icona del design industriale italiano al punto da guadagnarsi un posto nella collezione permanente del MoMA di New York.'),
(2,5,'testo','Senza essere laureato, da autodidatta, Cappellaro progettò questa macchina e le altre della serie, macchine destinate a cambiare il mondo.'),
(3,0,'titolo','Marca:'),
(3,1,'testo','Burroughs'),
(3,2,'titolo','Anno:'),
(3,3,'testo','1960'),
(3,5,'testo','“Ecco a voi. Questa è la nuova e più brillante addizionatrice Ten Key della Burroughs.” Nel 1960 iniziò a circolare un volantino che acclamava questa novità: non solo era un’addizionatrice ten key, ma definiva l’inizio di un’era in cui anche i colori delle macchine avevano la loro importanza.'),
(4,0,'titolo','Marca:'),
(4,1,'testo','Olivetti'),
(4,2,'titolo','Anno:'),
(4,3,'testo','1966'),
(4,5,'titolo','“Perottina”, un diminutivo per un passo da gigante.'),
(4,6,'testo','Il nome deriva dal suo progettista, Giorgio Perotto. Gli altri ingegneri che lavorarono al progetto furono Giovanni De Sandre e Gastone Garziera.'),
(4,7,'testo','L\'Olivetti Programma 101, o P101, è in effetti il primo desktop computer o "personal computer" al mondo. Con un linguaggio di programmazione (con condizioni logiche), una memoria interna, un sistema di salvataggio dei dati e del programma, la P101 era stata sviluppata per essere economica e facile da usare.'),
(4,8,'testo','Le applicazioni su cartolina magnetica non richiedevano la conoscenza del linguaggio di programmazione e oltre a ciò bisogna ricordare che i computer, fino a fine anni \'60, avevano le dimensioni di armadi e potevano occupare varie stanze, venivano gestiti da tecnici esperti e solitamente il risultato dell\' elaborazione (l\'output) era visualizzato su una telescrivente, o su nastri di carta perforata.'),
(4,9,'testo','Rispetto a quegli armadi dei calcolatori dell’epoca, la Perottina è una piccola principessa nel mondo dei computer.'),
(4,10,'testo','Con una Perottina si puó fare di tutto, anche andare sulla luna, letteralmente: è stata usata dalla NASA per la missione Apollo 11.'),
(5,0,'titolo','Marca:'),
(5,1,'testo','Olivetti'),
(5,2,'titolo','Anno:'),
(5,3,'testo','1967'),
(5,4,'testo','Descrizione: La Divisumma 26 GT, presentata nel 1967, con caratteristiche appena superiori a quelle della Divisumma 24, è munita di un totalizzatore e due memorie. Linee arrotondate? No grazie. Vengono abbandonate per il design a favore di quelle più squadrate, come nelle macchine da scrivere dell’epoca.. Natale Capellaro, già noto nella progettazione della Summa 15 per il brevetto del meccanismo a quattro vie, ha partecipato alla realizzazione meccanica.'),
(6,0,'titolo','Marca:'),
(6,1,'testo','Olivetti'),
(6,2,'titolo','Anno:'),
(6,3,'testo','1970'),
(6,4,'testo','La Logos 240, presentata nel 1971, fa parte della nuova linea di calcolatrici della Olivetti con elettronica a circuiti integrati. La memoria, a linea di ritardo magnetica, è simile a quella utilizzata sulla P101. Le aree operative (area stampa e tastiera) sono separate secondo la politica di design di M. Bellini.'),
(7,0,'titolo','Marca:'),
(7,1,'testo','Olivetti'),
(7,2,'titolo','Anno:'),
(7,3,'testo','1977'),
(7,4,'testo','È ora di dire basta agli hard disk grandi mezza sala da pranzo! Sia il drive che il nuovo supporto sono di dimensioni estremamente compatte, il "minidisco" è un piccolo floppy flessibile in mylar dal diametro di 6.5 cm, privo di ogni custodia di protezione.'),
(7,5,'testo','"maneggevole, di minimo ingombro, agevolmente archiviabile e spedibile, l’ideale per archiviare programmi o dati".'),
(7,6,'testo','La capacità di memorizzazione era di soli 3 kB (descritti nel depliant come "3000 caratteri"), ma sufficienti per la macchina che aveva appunto una memoria di soli 3 kB.');
