version: '3.7'

services:
  db:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - db_museo_informatica:/var/lib/mysql
volumes:
  db_museo_informatica:


