version: '3.7'

services:
  db:
    image: mariadb:10.4
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - xampp-db:/var/lib/mysql
volumes:
  xampp-db:
networks: 
  xampp-net:
